"""Stage A1 — per-date intermediate event-tape build.

Reads partitioned raw quotes + trades for ONE (ticker, date), runs the full
clean → NBBO → sign → merge → features pipeline, writes intermediate Parquet.

Two invocation modes:
  1. Direct:   +ticker=INTC +date=2025-04-15
  2. Manifest (SLURM array):  +manifest=data/manifests/ph1_clean.json +task_id=42

The manifest is generated by scripts/utils/make_manifest.py --kind clean.
"""
from __future__ import annotations

import json
from pathlib import Path

import hydra
from omegaconf import DictConfig

from diffmm.data import clean as clean_mod
from diffmm.data import features as feat_mod
from diffmm.data.tapes import build_intermediate_tape
from diffmm.io.manifest import write_meta
from diffmm.utils.logging import get_logger
from diffmm.utils.seeding import seed_all

log = get_logger("ph1_clean")


def _resolve_task(cfg: DictConfig) -> tuple[str, str]:
    if "ticker" in cfg and "date" in cfg:
        return str(cfg.ticker), str(cfg.date)
    task_id = cfg.get("task_id")
    manifest_path = cfg.get("manifest")
    if task_id is None or manifest_path is None:
        raise ValueError("must pass either +ticker=... +date=... or +task_id=... +manifest=...")
    manifest = json.loads(Path(manifest_path).read_text())
    entry = manifest[int(task_id)]
    return entry["ticker"], entry["date"]


def _build_clean_cfg(cfg: DictConfig) -> clean_mod.CleanConfig:
    return clean_mod.CleanConfig(
        quote=clean_mod.QuoteFilterConfig(
            keep_qu_cond=tuple(cfg.data.quote_filter.keep_qu_cond),
            drop_zero_quotes=cfg.data.quote_filter.drop_zero_quotes,
            drop_crossed_or_locked=cfg.data.quote_filter.drop_crossed_or_locked,
        ),
        trade=clean_mod.TradeFilterConfig(
            keep_first_char=tuple(cfg.data.trade_filter.keep_first_char),
            drop_modifiers=tuple(cfg.data.trade_filter.drop_modifiers),
            keep_corr=tuple(cfg.data.trade_filter.keep_corr),
            drop_rf=tuple(cfg.data.trade_filter.drop_rf),
            flag_dark_as_non_lit=cfg.data.trade_filter.flag_dark_as_non_lit,
        ),
        session=clean_mod.SessionConfig(
            session_start_et=cfg.data.session_start_et,
            session_end_et=cfg.data.session_end_et,
            timezone=cfg.data.timezone,
        ),
    )


def _build_feat_cfg(cfg: DictConfig) -> feat_mod.FeatureConfig:
    return feat_mod.FeatureConfig(
        vol_window_seconds=cfg.data.features.vol_window_seconds,
        imb_threshold=cfg.data.features.imb_threshold,
        vpin_n_buckets_per_day=cfg.data.features.vpin_n_buckets_per_day,
        vpin_window_buckets=cfg.data.features.vpin_window_buckets,
        morning_end_et_minutes=cfg.data.features.morning_end_et_minutes,
        midday_end_et_minutes=cfg.data.features.midday_end_et_minutes,
        timezone=cfg.data.timezone,
    )


@hydra.main(version_base=None, config_path="../configs", config_name="config")
def main(cfg: DictConfig) -> None:
    seed_all(cfg.seed)
    ticker, date = _resolve_task(cfg)
    log.info("building intermediate tape: ticker=%s date=%s", ticker, date)

    raw_dir = Path(cfg.data.raw_partitioned_dir) / ticker
    quotes_p = raw_dir / "quotes" / f"{date}.parquet"
    trades_p = raw_dir / "trades" / f"{date}.parquet"
    out = Path(cfg.data.intermediate_dir) / ticker / f"{date}.parquet"
    out.parent.mkdir(parents=True, exist_ok=True)

    clean_cfg = _build_clean_cfg(cfg)
    feat_cfg = _build_feat_cfg(cfg)

    df = build_intermediate_tape(
        ticker=ticker, date=date,
        raw_quotes_parquet=quotes_p, raw_trades_parquet=trades_p,
        clean_cfg=clean_cfg, feat_cfg=feat_cfg,
    )
    log.info("rows=%d  bytes_estimate=%.1fMB", df.height, df.estimated_size("mb"))

    df.write_parquet(out, compression="zstd", statistics=True)
    write_meta(
        out, seed=cfg.seed, config=cfg,
        creator_script="scripts/02_build_tapes.py",
        input_artifacts=[str(quotes_p), str(trades_p)],
    )
    log.info("wrote %s", out)


if __name__ == "__main__":
    main()
